### ISSUE TITLE
where's the executor/driver memory config?

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/bigtop#40]
In the `apache-spark` charm, we had driver and executor config options:

https://github.com/juju-solutions/layer-apache-spark/blob/master/config.yaml#L8

These would allow the user to change the defaults (1g) post deployment.  Why didn't this make it into the bigtop-spark charm?

If there's no good reason, let's bring those config opts back.  Fwiw, the logic behind those options in apache-spark is here:

https://github.com/juju-solutions/layer-apache-spark/blob/master/lib/charms/layer/apache_spark.py#L386

**Comment by ktsakalozos** [comment]
Lets re-add these configs. Added a card in the backlog.

**Comment by johnsca** [comment]
It looks like these are not exposed as configurable by Bigtop Spark's [init.pp](https://github.com/apache/bigtop/blob/master/bigtop-deploy/puppet/modules/spark/manifests/init.pp#L137)

**Comment by kwmonroe** [comment]
And these will need to be passed by the spark relation.  Bigtop zepp is becoming standalone, which means we won't know these values from the local machine's /etc/environment.

**Comment by kwmonroe** [comment]
These came back with [BIGTOP-2822](https://issues.apache.org/jira/browse/BIGTOP-2822), which takes advantage of the update to spark's init.pp in [BIGTOP-2821](https://issues.apache.org/jira/browse/BIGTOP-2821).

I mentioned the requirement to pass this config on the spark client relation, but I don't think that's necessary.  If Zepp users want different mem config, they'll need to set that in Zepp's spark interpreter (which already overrides spark master config).

Closing out.
