### ISSUE TITLE
Zookeeper charm is multiseries for xenial and xenial

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bigtop#43]
The series in zookeeper metadata.yaml gets merged with the series of the base layer and we end up with  a multiseries charm for xenial x2. Easy fix: remove series from metadata.yaml

**Comment by kwmonroe** [comment]
I'm not sure exactly which revision resolved this, but for sure >= rev 53 doesn't dupe the series:

https://api.jujucharms.com/charmstore/v5/zookeeper/archive/metadata.yaml
