### ISSUE TITLE
Spark environment variables not set

### ISSUE THREAD

**Issue by merlijn-sebrechts** [juju-solutions/bigtop#47]
the apache-spark sets a number of useful spark environment variables:

```
 cat /etc/environment | grep -i spark
PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/spark/bin:/usr/lib/hadoop/bin:/usr/lib/hadoop/sbin"
SPARK_JAR="hdfs:///user/ubuntu/share/lib/spark-assembly.jar"
SPARK_DRIVER_MEMORY="1g"
SPARK_EXECUTOR_MEMORY="1g"
SPARK_CONF_DIR="/etc/spark/conf"
PYSPARK_DRIVER_PYTHON="ipython"
SPARK_HOME="/usr/lib/spark"
```

This is not the case for the bigtop spark charm

```
cat /etc/environment | grep -i spark
MASTER="spark://172.28.0.15:7077"
```

Is this a bug or is this intentional? This causes installation of Apache Toree to fail, because it uses these env vars to find spark, even though stuff like pyspark is in the PATH.

**Comment by merlijn-sebrechts** [comment]
Note: "findspark" also expects at least SPARK_HOME to be set.

**Comment by kwmonroe** [comment]
Hey @galgalesh, some of those vars have been handled in [BIGTOP-2822](https://issues.apache.org/jira/browse/BIGTOP-2822) by configuring `spark-defaults.conf` (e.g.: `SPARK_*_MEMORY`):

```
$ cat /etc/spark/conf/spark-defaults.conf
...
spark.master yarn-client
spark.eventLog.enabled true
spark.eventLog.dir hdfs:///var/log/spark/apps
spark.history.fs.logDirectory hdfs:///var/log/spark/apps
spark.yarn.historyServer.address 172.31.53.12:18080
spark.history.ui.port 18080
spark.shuffle.service.enabled false
spark.driver.extraLibraryPath /usr/lib/hadoop/lib/native
spark.executor.extraLibraryPath /usr/lib/hadoop/lib/native
spark.driver.memory 1g
spark.executor.memory 1g
```

Others, like `SPARK_HOME`, are available by sourcing `/etc/spark/conf/spark-env.sh`:

```
$ sudo grep -r SPARK /etc/spark/conf
...
/etc/spark/conf/spark-env.sh:export SPARK_HOME=${SPARK_HOME:-/usr/lib/spark}
/etc/spark/conf/spark-env.sh:export SPARK_LOG_DIR=${SPARK_LOG_DIR:-/var/log/spark}
/etc/spark/conf/spark-env.sh:export SPARK_DAEMON_JAVA_OPTS="-Dspark.deploy.recoveryMode=NONE"
/etc/spark/conf/spark-env.sh:export STANDALONE_SPARK_MASTER_HOST=172.31.53.12
/etc/spark/conf/spark-env.sh:export SPARK_MASTER_PORT=7077
/etc/spark/conf/spark-env.sh:export SPARK_MASTER_IP=$STANDALONE_SPARK_MASTER_HOST
/etc/spark/conf/spark-env.sh:export SPARK_MASTER_URL=yarn-client
/etc/spark/conf/spark-env.sh:export SPARK_MASTER_WEBUI_PORT=8080
/etc/spark/conf/spark-env.sh:export SPARK_WORKER_DIR=${SPARK_WORKER_DIR:-/var/run/spark/work}
/etc/spark/conf/spark-env.sh:export SPARK_WORKER_PORT=7078
/etc/spark/conf/spark-env.sh:export SPARK_WORKER_WEBUI_PORT=8081
```

The values in both config locations should automatically be honored when working in `spark shell` or using `spark-submit`.  Does this work for you, or are you dependent on this config being available in `/etc/environment`?

As an aside, the `spark-submit` action on the spark charm now also allows you to set `spark-submit` args (`options` and `job-args`). This may be worth a look if you are interested in overriding the spark env for jobs submitted with this action:

https://github.com/apache/bigtop/blob/master/bigtop-packages/src/charm/spark/layer-spark/actions.yaml#L49

**Comment by merlijn-sebrechts** [comment]
Interesting!

A number of spark tools expects at least the `SPARK_HOME` to be set. One example is the installation scripts for the `apache toree` kernel for the Jupyter notebook.

I can hack around it using `/etc/spark/conf/spark-env.sh` but it would still be better if you could add these variables to `/etc/environment`. This will make a lot more stuff work out-of-the-box with the Charm.

**Comment by kwmonroe** [comment]
Ack @galgalesh - thx for the feedback.  I'll wire this into the spark charm.

**Comment by kwmonroe** [comment]
@galgalesh I included `SPARK_HOME` in `/etc/environment` while refactoring our Spark-Bench support:

https://github.com/apache/bigtop/pull/246/files#diff-78ecc10e0df33a06b35b79f2a9429222R317

This has tested well across the clouds and is available in spark-51 and above:

https://jujucharms.com/spark/

I'm closing this out, but please re-open if you come across additional envars that would be useful to include in `/etc/environment`.  Thanks!

**Comment by merlijn-sebrechts** [comment]
Great, both findspark and Apache Toree work now without any config!
