### ISSUE TITLE
cs:spark-34 install hook fails on restricted network environment

### ISSUE THREAD

**Issue by verterok** [juju-solutions/bigtop#49]
Hi,

While trying to move from apache-spark charm to cs:spark-34, we encountered some issues when deploying on a restricted network.

1. gcc is missing, and the hook install is trying to build netifaces module, failing with: http://paste.ubuntu.com/24494765/, "solved" by manually run: apt-get install build-essential

1. later it failed trying to fetch modules from puppetlabs: http://paste.ubuntu.com/24495398/

The model used for the deploy is configured to use a http(s) proxy in order to be able to reach the internet, but looks like the charm needs more than github access (besides the gcc issue)

**Comment by kwmonroe** [comment]
> gcc is missing, and the hook install is trying to build netifaces module, failing with: http://paste.ubuntu.com/24494765/, "solved" by manually run: apt-get install build-essential 

For some reason, my cloud and lxd images already include build-essential, so I never ran into this. 
 I've added b-e to the bigtop base layer package list:  https://github.com/juju-solutions/layer-apache-bigtop-base/commit/d11ae1038c89ae88332e21cfe8cc0bfe23680d31#diff-8d6683ea7efc34cfd86d2121c50b8acbR12

This should make it out into a charm release later this week.

> later it failed trying to fetch modules from puppetlabs: http://paste.ubuntu.com/24495398/

I'm working on a PR to pull the puppetlabs and github resources into the charm.  As long as you can get to the charm store, that should fix this.

**Comment by kwmonroe** [comment]
@verterok we now pack puppet resources into the charm and use a proper juju resource for the required bigtop source.  When you get a chance, try spark-36:

https://jujucharms.com/spark/36

I'm not sure what you'll hit next, but this should at least get you past your original gcc / puppetlabs / github cloning issues.
